services:
  docs:
    image: euroleague_insights_local_docs
    container_name: euroleague_insights_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./euroleague_insights:/app/euroleague_insights:z
    ports:
      - '9000:9000'
    command: /start-docs
